# test against this version of Node.js
environment:
  matrix:
  # node.js
  - nodejs_version: "6"

# install Sripts. (run after repo cloning)
install:
  # get he latedt stable version of Node.js or io.js
  -ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test Scripts.
test_script:
  # output useful info for debugging
  - node --version
  - npm --version
  # run test
  - npm test

# Don't build.
build: off
